create table public."Rooms" (
  id bigint generated by default as identity not null,
  name character varying not null,
  type character varying null,
  price double precision null,
  description character varying null,
  id_rating bigint null,
  constraint Rooms_pkey primary key (id)
) TABLESPACE pg_default;

INSERT INTO "public"."Rooms" ("id", "name", "type", "price", "description", "id_rating") VALUES ('1', 'Habitación Estándar', 'Estándar', '850', 'Cómoda habitación con cama matrimonial, aire acondicionado y baño privado.', '1'), ('2', 'Suite Ejecutiva', 'Suite', '1800', 'Espaciosa suite con sala de estar, escritorio, minibar y vista a la ciudad.', '2'), ('3', 'Habitación Doble', 'Doble', '950', 'Dos camas individuales, TV por cable y baño compartido.', '3'), ('5', 'Habitación Familiar', 'Familiar', '1500', 'Amplia habitación con 2 camas matrimoniales, ideal para familias de 4 personas.', '5');